### PR TITLE
Ensure etcd-backup-operator cannot be scheduled on the same node as chart-operator

### PR DESCRIPTION
**Pull request by glitchcrab**
towards https://github.com/giantswarm/giantswarm/issues/20494

### CODE REVIEW

**Comment by fiunchinho** [comment]
Wouldn't be simpler just to choose a different port? In my head it's more disruptive to deal with the scheduler than changing the port number, but I understand nothing prevents another app from conflicting with the new chosen port anyway.

**Comment by glitchcrab** [comment]
> port number, but I understand nothing prevents another app from conflicting with the new chosen port anyway.

I don't have the full context here as the main discussion was whilst I was off, but I believe there was a reason why we couldn't change the port on either operator - possibly because something else expects them to be listening on port 8000. Can someone from @giantswarm/team-rocket add some more info?

**Comment by tfussell** [comment]
If I understand correctly, etcd-backup-operator needs hostNetwork so it can access etcd on the master node without network policies. And chart-operator needs hostNetwork during bootstrapping because it is installed before CNI is available. If this is correct, we may be able to make chart-operator not use hostNetwork once it is installed by the app platform (i.e. after initial MC bootstrap).

**Comment by tfussell** [comment]
Also etcd-backup-operator has to run on the master so if we're going to use antiAffinity maybe it should be on chart-operator instead.

**Comment by whites11** [comment]
> Also etcd-backup-operator has to run on the master so if we're going to use antiAffinity maybe it should be on chart-operator instead.

the question is, why don't we just change the port for either operator to avoid the conflict? Should be easy, shouldn't it

**Comment by glitchcrab** [comment]
closing in favour of #295

**Pull request closed without merging**
