### PR TITLE
migrate-to-etcdv3client

### PR DESCRIPTION
**Pull request by calvix**
use `etcd v3client` library instead of the `etcdctl` binary file, migration is necessary for implementing a proper etcd backup solution for CAPI clusters

leaving etcdv2 as it is, no point updating code there

https://github.com/giantswarm/roadmap/issues/1006

### CODE REVIEW

**Comment by calvix** [comment]
```
{"caller":"github.com/giantswarm/etcd-backup-operator/v3/service/controller/resource/etcdbackup/create_running_v3.go:48","controller":"etcd-backup-operator-etcd-backup-controller","event":"update","level":"debug","loop":"34","message":"Starting v3 backup on instance zj88t","object":"/etcd-backup-20220704092636","resource":"etcd-backup","time":"2022-07-04T09:34:13.75036+00:00","version":"749151627"}
{"caller":"github.com/giantswarm/etcd-backup-operator/v3/service/controller/resource/etcdbackup/backup.go:23","controller":"etcd-backup-operator-etcd-backup-controller","event":"update","level":"debug","loop":"34","message":"Attempt number 1 for zj88t","object":"/etcd-backup-20220704092636","resource":"etcd-backup","time":"2022-07-04T09:34:14.053672+00:00","version":"749151627"}
{"caller":"github.com/giantswarm/etcd-backup-operator/v3/service/controller/resource/etcdbackup/backup.go:50","controller":"etcd-backup-operator-etcd-backup-controller","event":"update","level":"debug","loop":"34","message":"Creating backup file","object":"/etcd-backup-20220704092636","resource":"etcd-backup","time":"2022-07-04T09:34:14.053707+00:00","version":"749151627"}
{"caller":"github.com/giantswarm/micrologger@v1.0.0/logger.go:66","level":"debug","message":"Compacting etcd instance","time":"2022-07-04T09:34:14.053722+00:00"}
{"caller":"github.com/giantswarm/micrologger@v1.0.0/logger.go:66","level":"debug","message":"Revision is 76465835","time":"2022-07-04T09:34:14.450222+00:00"}
{"caller":"github.com/giantswarm/micrologger@v1.0.0/logger.go:66","level":"debug","message":"Compacted etcd instance","time":"2022-07-04T09:34:14.553564+00:00"}
{"caller":"github.com/giantswarm/micrologger@v1.0.0/logger.go:66","level":"debug","message":"Defragging etcd instance","time":"2022-07-04T09:34:14.553603+00:00"}
{"caller":"github.com/giantswarm/micrologger@v1.0.0/logger.go:66","level":"debug","message":"Defragged etcd instance","time":"2022-07-04T09:34:15.05265+00:00"}
{"Created temporary directory: /tmp/724902839":"(MISSING)","caller":"github.com/giantswarm/etcd-backup-operator/v3/pkg/etcd/etcdv3.go:156","time":"2022-07-04T09:34:15.052841+00:00"}
{"level":"info","ts":"2022-07-04T09:34:15.052Z","logger":"etcd-client","caller":"v3@v3.5.4/maintenance.go:211","msg":"opened snapshot stream; downloading"}
{"level":"info","ts":"2022-07-04T09:34:19.550Z","logger":"etcd-client","caller":"v3@v3.5.4/maintenance.go:219","msg":"completed snapshot read; closing"}
{"caller":"github.com/giantswarm/etcd-backup-operator/v3/pkg/etcd/etcdv3.go:118","level":"info","msg":"Etcd v3 backup created successfully","time":"2022-07-04T09:34:28.250902+00:00"}

```

**Comment by calvix** [comment]
looks like its working, I am surprised TBH :p

**Comment by calvix** [comment]
I can see backups in the s3 bucket as well

**Review by whites11 — APPROVED** [review]
A very much needed improvement, well done!

**Pull request merged**
