### PR TITLE
Added values.schema.json file to validate helm values

### PR DESCRIPTION
**Pull request by fiunchinho**

### CODE REVIEW

**Comment by fiunchinho** [comment]
@ubergesundheit can you help me with this? I added the schema, and made the type of the field to be `null` and `string`, but `kubeval` still complains.

**Review by whites11 — APPROVED** [review]
Let's do it

**Comment by ubergesundheit** [comment]
Ping @giantswarm/team-halo no idea how kubeval works

**Comment by fiunchinho** [comment]
I think it was failing because the `Deployment` resource expected a string. Not because the passed value was not a string, as I thought.

**Pull request merged**
